import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/layout/ThemeProvider";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { Toaster } from "react-hot-toast";
import { GoogleAnalytics } from "@/components/layout/GoogleAnalytics";
import { Analytics } from "@vercel/analytics/next";
import { SITE_NAME, SITE_DESCRIPTION, SITE_URL } from "@/lib/utils";
import { SavedDuasProvider } from "@/contexts/SavedDuasContext";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    template: `%s | ${SITE_NAME}`,
    default: `${SITE_NAME} – Authentic Islamic Duas with Arabic & Sources`,
  },
  description: SITE_DESCRIPTION,
  keywords: [
    "dua",
    "duas",
    "islamic prayer",
    "supplication",
    "arabic dua",
    "dua before sleeping",
    "dua for anxiety",
    "sahih dua",
    "muslim dua",
    "islamic supplication",
    "hisn al muslim",
    "quran dua",
    "hadith dua",
  ],
  authors: [{ name: "DuaVault" }],
  creator: "DuaVault",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: `${SITE_NAME} – Authentic Islamic Duas`,
    description: SITE_DESCRIPTION,
    // OG image auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: `${SITE_NAME} – Authentic Islamic Duas`,
    description: SITE_DESCRIPTION,
    // OG image auto-generated by app/opengraph-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  verification: {
    google: process.env.NEXT_PUBLIC_GOOGLE_VERIFICATION,
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#fdf8f0" },
    { media: "(prefers-color-scheme: dark)", color: "#022c22" },
  ],
  width: "device-width",
  initialScale: 1,
  // Required for env(safe-area-inset-*) to return real values on notched
  // iPhones and modern Android devices with gesture navigation bars.
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning className={inter.variable}>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Amiri:ital,wght@0,400;0,700;1,400;1,700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="min-h-screen flex flex-col">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SavedDuasProvider>
          <Navbar />
          {/* pb-bottom-nav clears the bottom tab bar + iOS/Android safe area inset */}
          <main className="flex-1 pb-bottom-nav md:pb-0">{children}</main>
          <div className="hidden md:block"><Footer /></div>
          <Toaster
            position="bottom-center"
            // Offset above the bottom nav (64px) + any safe-area on notched devices
            containerStyle={{ bottom: "calc(4.5rem + env(safe-area-inset-bottom, 0px))" }}
            toastOptions={{
              className:
                "!bg-white dark:!bg-emerald-900 !text-stone-800 dark:!text-stone-100 !shadow-lg !rounded-xl !text-sm",
              duration: 2500,
            }}
          />
          </SavedDuasProvider>
        </ThemeProvider>
        {process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID && (
          <GoogleAnalytics gaId={process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID} />
        )}
        <Analytics />
      </body>
    </html>
  );
}
